// <auto-generated />
namespace Tethys.Observer.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Room_Department_Not_Required : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Room_Department_Not_Required));
        
        string IMigrationMetadata.Id
        {
            get { return "201409201525175_Room_Department_Not_Required"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
