// <auto-generated />
namespace Tethys.Observer.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Room_Location_Many_To_Many : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Room_Location_Many_To_Many));
        
        string IMigrationMetadata.Id
        {
            get { return "201409221432292_Room_Location_Many_To_Many"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
