// <auto-generated />
namespace Tethys.Observer.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Unique_Room_For_Department : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Unique_Room_For_Department));
        
        string IMigrationMetadata.Id
        {
            get { return "201409221442386_Unique_Room_For_Department"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
