// <auto-generated />
namespace Tethys.Observer.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Department_Name : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Department_Name));
        
        string IMigrationMetadata.Id
        {
            get { return "201409220828039_Department_Name"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
